services:

  web:
    build: .
    container_name: employee_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: employee_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: